const countryMap = {
  "United States of America": "USA",
  Mexico: "MEX",
  Nigeria: "NGA",
  Lebanon: "LBN",
  Russia: "RUS",
  "Saudi Arabia": "SAU",
  Angola: "AGO",
  Egypt: "EGY",
  "South Africa": "ZAF",
  India: "IND",
  Ukraine: "UKR",
  Azerbaijan: "AZE",
  China: "CHN",
  Colombia: "COL",
  Niger: "NER",
  Libya: "LBY",
  Brazil: "BRA",
  Mali: "MLI",
  Indonesia: "IDN",
  Iraq: "IRQ",
  Iran: "IRN",
  "South Sudan": "SSD",
  Venezuela: "VEN",
  "Burkina Faso": "BFA",
  Germany: "DEU",
  "United Kingdom": "GBR",
  Kuwait: "KWT",
  Canada: "CAN",
  Argentina: "ARG",
  Japan: "JPN",
  Austria: "AUT",
  Spain: "ESP",
  Estonia: "EST",
  Hungary: "HUN",
  Australia: "AUS",
  Morocco: "MAR",
  Greece: "GRC",
  Qatar: "QAT",
  Oman: "OMN",
  Liberia: "LBR",
  Denmark: "DNK",
  Malaysia: "MYS",
  Jordan: "JOR",
  Syria: "SYR",
  Ethiopia: "ETH",
  Norway: "NOR",
  Ghana: "GHA",
  Kazakhstan: "KAZ",
  Pakistan: "PAK",
  Gabon: "GAB",
  "United Arab Emirates": "ARE",
  Algeria: "DZA",
  Turkey: "TUR",
  Cyprus: "CYP",
  Belize: "BLZ",
  Poland: "POL",
};

export const getCountryCode = (name) => {
  return countryMap[name] || name;
};
